server:
  port: 8082
spring:
  application:
    name: consumer-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    #服务注册信息         服务名                          服务所在ip               服务端口
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
