server:
  port: 8083
spring:
  application:
    name: provider-server
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: thinker
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    #服务注册信息         服务名                          服务所在ip               服务端口
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
#mybatis:
#  mapper-locations: classpath:mybatis/mappers/*.xml
#  config-location: classpath:mybatis/mybatis-config.xml
#  type-aliases-package: com.xcr.test.pojo