mybatis:
  mapper-locations: classpath:mybatis/mappers/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.xcr.test.pojo

#spring:
#  datasource:
#    driver-class-name: org.gjt.mm.mysql.Driver
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: thinker

server:
  port: 2020

#pagehelper:
#  reasonable: true
#  dialect: mysql
#  support-methods-arguments: true
